apiVersion: v1
kind: Service
metadata:
  name: base-prospect-back
  namespace: base-prospect
  labels:
    app: base-prospect-back
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app: base-prospect-back
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-prospect-back
  namespace: base-prospect
  labels:
    app: base-prospect-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-prospect-back
  template:
    metadata:
      labels:
        app: base-prospect-back
    spec:
      containers:
      - name: base-prospect-back
        image: youchafiki/base-prospect:latest
        ports:
        - containerPort: 8082
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.5"
          requests:
            memory: "128Mi"
            cpu: "0.25"
        
