apiVersion: v1
kind: Service
metadata:
  name: greeting
  labels:
    app: greeting
spec:
  ports:
  - name: http
    port: 8086
    targetPort: 8080
  selector:
    app: greeting
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  labels:
    app: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: thomaspoignant/hello-world-rest-json
        ports:
        - containerPort: 8080

        
