apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: base-prospect
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
