apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-consul-pvc0
  namespace: base-prospect
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4.5Gi
